### ISSUE TITLE
api-anpassung auch in tibexport.php notwendig

### ISSUE THREAD

**Issue by larsneo** [humpataa/tibber-daily-view#3]
die aktuelle api-anpassung aus tib.php sollte auch noch in tibexport.php nachgezogen werden:

`//$datetime->modify('+1 day');`
bzw.
`$json = '{"query":"{viewer {homes {timeZone id address {postalCode city}consumption(resolution: HOURLY first: 24 after: \"'.$cursor.'\") {nodes {from to cost unitPrice unitPriceVAT consumption consumptionUnit}}}}}"}';`

**Comment by larsneo** [comment]
consumption und consumption unit sind im stream allerdings sowieso recht eigenwillig.
![grafik](https://github.com/user-attachments/assets/8da68723-3905-4586-9949-4e1c95f5d695)
![grafik](https://github.com/user-attachments/assets/752390e0-181f-4827-93d4-e4cc2f7dfe3d)

**Comment by humpataa** [comment]
natürlich, danke für den hinweis, ist korrigiert.

was meinst du mit "eigenwillig"?
bei mir sieht das sehr ordentlich aus (auf den richtigen CSV Import im Office / Numbers achten!):

<img width="968" alt="Bildschirmfoto 2024-10-20 um 13 27 33" src="https://github.com/user-attachments/assets/bcb74781-1c43-4262-ba19-4428d015d873">

**Comment by larsneo** [comment]
thx für den schnellen fix - und chapeau zur umsetzung insgesamt

was die darstellung der consumption angeht hast du recht - mein libreoffice verhunzt die consumption tatsächlich erst bei der anzeige *nach* dem import, in der vorschau beim öffnen sieht es noch korrekt aus. muss ich mir mal in ruhe anschauen.
