### ISSUE TITLE
Schönheitskorrektur der Anzeige von Stunden-Preis und Stunden-kWh

### ISSUE THREAD

**Issue by larsneo** [humpataa/tibber-daily-view#4]
Für eine gleichmässige Anzeige der um 90 Grad gedrehten Stundenwerte für Verbrauch und Kosten in tib.php bietet sich vielleicht zusätzlich noch number_format an:

`			echo '<text x="5" y="'.($stepbreite / 2).'" font-size="small+1" text-anchor="start" transform="translate('.($key * $stepbreite + 55).','.($hoehe + 20).') rotate(-90)">'.number_format(($consumption),3).' kWh </text>';
`

bzw.

`			echo '<text x="5" y="'.($stepbreite / 2).'" font-size="small+1" text-anchor="start" transform="translate('.($key * $stepbreite + 55).', 60) rotate(-90)">'.number_format((ceil($cost*100)/100),2).' € </text>';
`

![grafik](https://github.com/user-attachments/assets/da2bab2c-0e54-429e-b07b-5cb341c2ee86)

**Comment by humpataa** [comment]
done
